apiVersion: v1
kind: ServiceAccount
metadata:
  name: volcreator-sa
  namespace: glusterfs

---

#-- The SA just needs to be able to:
#-- - exec into a gluster pod (to set quotas)
#-- - create PVs
#--
#-- But for now, just grant everything :(
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: volcreator-admin
  namespace: glusterfs
subjects:
- kind: ServiceAccount
  name: volcreator-sa
  namespace: glusterfs
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: batch/v1
kind: Job
metadata:
  name: volcreator
  namespace: glusterfs
spec:
  template:
    metadata:
      name: volcreator
    spec:
      serviceAccountName: volcreator-sa
      containers:
      - name: volcreator
        image: johnstrunk/volcreator:latest
        #command: 
        #- "/bin/bash"
        #args:
        #- "-c"
        #- "sleep 999999"
        args:
        #-- This needs to match volumes.glusterfs.endpoints below
        - "glusterfs-cluster"
        #-- This needs to match volumes.glusterfs.path below
        - "testvol"
        - "/data"
        - "0"
        - "100"
        volumeMounts:
        - name: data
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data
        glusterfs:
          endpoints: glusterfs-cluster
          path: testvol
          readOnly: false
