---

- name: "Installing Prerequisite packages"
  yum:
        name:
          - git
          - yum-utils
          - python-setuptools
          - python-devel
        state: latest
- name: insatll pip
  easy_install:
    name: pip
    state: latest
- name: install openshift
  shell: |
        sudo pip install -U setuptools
        sudo pip install --ignore-installed openshift

- name: git clone rook
  git:
    repo: https://github.com/rook/rook
    dest: /root/rook

- name: install ceph common
  shell: >
     kubectl create -f /root/rook/cluster/examples/kubernetes/ceph/common.yaml

- name: install operator
  shell: >
     kubectl create -f /root/rook/cluster/examples/kubernetes/ceph/operator.yaml

- name: Wait for operator to be running
  shell: "kubectl get -n rook-ceph po | grep -c Running"
  register: task_result
  ignore_errors: true
  until: task_result.stdout >= "2"
  delay: 10
  retries: 60
  changed_when: false

- name: install ceph cluster
  shell: >
     kubectl create -f /root/rook/cluster/examples/kubernetes/ceph/cluster-test.yaml

- name: Wait for monintors to be running
  shell: "kubectl get -n rook-ceph po -l app=rook-ceph-mon | grep -c Running"
  register: task_result
  ignore_errors: true
  until: task_result.stdout >= "1"
  delay: 10
  retries: 60
  changed_when: false

- name: install tool-box
  shell: >
     kubectl create -f /root/rook/cluster/examples/kubernetes/ceph/toolbox.yaml

- name: create pool
  shell: >
    kubectl create -f /root/rook/cluster/examples/kubernetes/ceph/pool-test.yaml
